## Custom config for KrazyOPMod

bannedwords:
      - dick
      - fuck
      - cunt
      - shit
      - nigger
      - asshole
      - nigg
      - bitch
      - pussy
      - penis
      - vagina
      - slut
      - smd
      - tits
      - titties
      - cum
      - wank
      - faggot
      - seks
      - sex
      - douchebag
      - blowjob
      - milf
      - hump
      - testicle
      - rimjob
      - handjob
      - mastrubate
      - gaylord    
      - nigga
      - fucking
      - motherfucker
      - ass
      
builders:
    - cyro1999
    - taahthepenguin
    - redseamc
    - camnop